name: VictoriaMetrics Agent Addon for Home Assistant
version: "0.1"
slug: victoriametrics_agent
description: VictoriaMetrics Agent Addon for Home Assistant
url: "https://github.com/ThePnx/home-assistant-addon-victoriametrics-agent"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
webui: "http://[HOST]:[PORT:8429]/metrics"

ports:
  8429/tcp: 8429

map:
  - share:rw

options:
  remoteWrite:
    url: "http://[victoriametrics-host-ip]/api/v1/write"

  promscrape:
    enabled: false
    config: "/path/to/prometheus.yml"
    config.strictParse: true

  httpAuth:
    enabled: false
    username: ""
    password: ""

  httpListenAddr:
    tcp: ""
    useProxyProtocol: ""

  tls:
    enabled: false
    certFile: "/path/to/cert/file"
    keyFile: "/path/to/key/file"
    minVersion: "TLS13"

schema:
  remoteWrite:
    url: str?

  promscrape:
    enabled: bool
    config: str?
    config.strictParse: bool

  httpAuth:
    enabled: bool
    username: str?
    password: password?

  httpListenAddr:
    tcp: str?
    useProxyProtocol: str?

  tls:
    enabled: bool
    certFile: str?
    keyFile: str?
    minVersion: str?